# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wald < Formula
  desc "Manage git worktrees for configured projects"
  homepage "https://github.com/felixjung/wald"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixjung/wald/releases/download/v1.1.0/wald_1.1.0_darwin_x86_64.tar.gz"
      sha256 "51913ec79cff3881982f0c6be4906fffe90c9432121a48b5c14312b41a141713"

      define_method(:install) do
        bin.install "wald"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixjung/wald/releases/download/v1.1.0/wald_1.1.0_darwin_arm64.tar.gz"
      sha256 "1210e3cbb2e0183682f321db4e9d19b519fc54b9729b213631ae39eddad510fa"

      define_method(:install) do
        bin.install "wald"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixjung/wald/releases/download/v1.1.0/wald_1.1.0_linux_x86_64.tar.gz"
      sha256 "f4ab3d2e5edf308b3bbb4341668aa570752134a5b259825edcb1148a25d39cd8"
      define_method(:install) do
        bin.install "wald"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixjung/wald/releases/download/v1.1.0/wald_1.1.0_linux_arm64.tar.gz"
      sha256 "a26a8d76547eb5d65fba2e58575d40df9f8dce5eadcf1916c041cb1802ccf4f9"
      define_method(:install) do
        bin.install "wald"
      end
    end
  end

  test do
    assert_match "Manage git worktrees", shell_output("#{bin}/wald --help")
  end
end
