# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wald < Formula
  desc "Manage git worktrees for configured projects"
  homepage "https://github.com/felixjung/wald"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixjung/wald/releases/download/v1.2.0/wald_1.2.0_darwin_x86_64.tar.gz"
      sha256 "b7ea12393f6a486a2c7f77e0dcdf94c8f6971391c5909f31a5106ee7a8cd51eb"

      define_method(:install) do
        bin.install "wald"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixjung/wald/releases/download/v1.2.0/wald_1.2.0_darwin_arm64.tar.gz"
      sha256 "96cf304b8d61c3f32208d4760f0d75ab486a21dad5d417ca5b6ef6d25b5f6353"

      define_method(:install) do
        bin.install "wald"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixjung/wald/releases/download/v1.2.0/wald_1.2.0_linux_x86_64.tar.gz"
      sha256 "342dc2127db38ce81e28dc2b38a1be2b51aaf3f4a8cbed156d4a59934e5665a6"
      define_method(:install) do
        bin.install "wald"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixjung/wald/releases/download/v1.2.0/wald_1.2.0_linux_arm64.tar.gz"
      sha256 "89963282a4dba7b7ca6ef94880b917cdf94ddd6a802f4b5a11a52d0654db6bb7"
      define_method(:install) do
        bin.install "wald"
      end
    end
  end

  test do
    assert_match "Manage git worktrees", shell_output("#{bin}/wald --help")
  end
end
