# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wald < Formula
  desc "Manage git worktrees for configured projects"
  homepage "https://github.com/felixjung/wald"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixjung/wald/releases/download/v1.3.0/wald_1.3.0_darwin_x86_64.tar.gz"
      sha256 "70e5104792ea65c99bc7b7f2dba1481f2be3b4154da8f0e7aff320763880b7bd"

      define_method(:install) do
        bin.install "wald"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixjung/wald/releases/download/v1.3.0/wald_1.3.0_darwin_arm64.tar.gz"
      sha256 "02cbeb90ff1bacf0b2e5fd7a8db49110df45120306721c7db8f5136c55e7a654"

      define_method(:install) do
        bin.install "wald"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixjung/wald/releases/download/v1.3.0/wald_1.3.0_linux_x86_64.tar.gz"
      sha256 "db31c288b1f02b828ac90c7990710a19ddb477920a7cc4cb3c25c18c171235bd"
      define_method(:install) do
        bin.install "wald"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixjung/wald/releases/download/v1.3.0/wald_1.3.0_linux_arm64.tar.gz"
      sha256 "883d972f7cb15ef29aea2be1bee6317796548778cc69033704575194db05515c"
      define_method(:install) do
        bin.install "wald"
      end
    end
  end

  test do
    assert_match "Manage git worktrees", shell_output("#{bin}/wald --help")
  end
end
